// Auto-generated by RAudioGenerator
using UnityEngine;

public static partial class R
{
    public static class Audio
    {
        public static AudioClip BrokenPanel;
        public static AudioClip CloudShow;
        public static AudioClip lampOut;
        public static AudioClip Lia;
        public static AudioClip LOFIMUSIC;
        public static AudioClip MouseClicked;
        public static AudioClip MouseInButton;
        public static AudioClip PanelIn;
        public static AudioClip PanelOut;
        public static AudioClip pencil_writing;
        public static AudioClip pop_fx;
        public static AudioClip SpeakSound;
        public static AudioClip zvuk_notyi_do_vo_vtoroy_oktave;
        public static AudioClip click;
        public static AudioClip click_2;
        public static AudioClip misc_menu;
        public static AudioClip misc_menu_2;
        public static AudioClip misc_menu_4;
        public static AudioClip misc_sound;
        public static AudioClip negative;
        public static AudioClip negative_2;
        public static AudioClip positive;
        public static AudioClip save;
        public static AudioClip sharp_echo;
        public static AudioClip Wrong_Error;
    }

    public static void InitAudio()
    {
        Audio.BrokenPanel = Resources.Load<AudioClip>("Audio/BrokenPanel");
        Audio.CloudShow = Resources.Load<AudioClip>("Audio/CloudShow");
        Audio.lampOut = Resources.Load<AudioClip>("Audio/lampOut");
        Audio.Lia = Resources.Load<AudioClip>("Audio/Lia");
        Audio.LOFIMUSIC = Resources.Load<AudioClip>("Audio/LOFIMUSIC");
        Audio.MouseClicked = Resources.Load<AudioClip>("Audio/MouseClicked");
        Audio.MouseInButton = Resources.Load<AudioClip>("Audio/MouseInButton");
        Audio.PanelIn = Resources.Load<AudioClip>("Audio/PanelIn");
        Audio.PanelOut = Resources.Load<AudioClip>("Audio/PanelOut");
        Audio.pencil_writing = Resources.Load<AudioClip>("Audio/pencil-writing");
        Audio.pop_fx = Resources.Load<AudioClip>("Audio/pop-fx");
        Audio.SpeakSound = Resources.Load<AudioClip>("Audio/SpeakSound");
        Audio.zvuk_notyi_do_vo_vtoroy_oktave = Resources.Load<AudioClip>("Audio/zvuk-notyi-do-vo-vtoroy-oktave");
        Audio.click = Resources.Load<AudioClip>("Audio/Bank/click");
        Audio.click_2 = Resources.Load<AudioClip>("Audio/Bank/click_2");
        Audio.misc_menu = Resources.Load<AudioClip>("Audio/Bank/misc_menu");
        Audio.misc_menu_2 = Resources.Load<AudioClip>("Audio/Bank/misc_menu_2");
        Audio.misc_menu_4 = Resources.Load<AudioClip>("Audio/Bank/misc_menu_4");
        Audio.misc_sound = Resources.Load<AudioClip>("Audio/Bank/misc_sound");
        Audio.negative = Resources.Load<AudioClip>("Audio/Bank/negative");
        Audio.negative_2 = Resources.Load<AudioClip>("Audio/Bank/negative_2");
        Audio.positive = Resources.Load<AudioClip>("Audio/Bank/positive");
        Audio.save = Resources.Load<AudioClip>("Audio/Bank/save");
        Audio.sharp_echo = Resources.Load<AudioClip>("Audio/Bank/sharp_echo");
        Audio.Wrong_Error = Resources.Load<AudioClip>("Audio/Bank/Wrong Error");
    }
}
